---
- name: Deploy App1
  hosts: balance
  become: true
  tasks:
    - name: deploy web1web2
      docker_container:
        name: app1
        image: repo/app1
        state: started
        restart_policy: always
        published_ports: 80:80
